/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boole8_12 (
    input [3:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] out
  );
  
  
  
  wire [1-1:0] M_bobo0_out;
  reg [4-1:0] M_bobo0_alufn;
  reg [2-1:0] M_bobo0_a;
  boole1_24 bobo0 (
    .alufn(M_bobo0_alufn),
    .a(M_bobo0_a),
    .out(M_bobo0_out)
  );
  
  wire [1-1:0] M_bobo1_out;
  reg [4-1:0] M_bobo1_alufn;
  reg [2-1:0] M_bobo1_a;
  boole1_24 bobo1 (
    .alufn(M_bobo1_alufn),
    .a(M_bobo1_a),
    .out(M_bobo1_out)
  );
  
  wire [1-1:0] M_bobo2_out;
  reg [4-1:0] M_bobo2_alufn;
  reg [2-1:0] M_bobo2_a;
  boole1_24 bobo2 (
    .alufn(M_bobo2_alufn),
    .a(M_bobo2_a),
    .out(M_bobo2_out)
  );
  
  wire [1-1:0] M_bobo3_out;
  reg [4-1:0] M_bobo3_alufn;
  reg [2-1:0] M_bobo3_a;
  boole1_24 bobo3 (
    .alufn(M_bobo3_alufn),
    .a(M_bobo3_a),
    .out(M_bobo3_out)
  );
  
  wire [1-1:0] M_bobo4_out;
  reg [4-1:0] M_bobo4_alufn;
  reg [2-1:0] M_bobo4_a;
  boole1_24 bobo4 (
    .alufn(M_bobo4_alufn),
    .a(M_bobo4_a),
    .out(M_bobo4_out)
  );
  
  wire [1-1:0] M_bobo5_out;
  reg [4-1:0] M_bobo5_alufn;
  reg [2-1:0] M_bobo5_a;
  boole1_24 bobo5 (
    .alufn(M_bobo5_alufn),
    .a(M_bobo5_a),
    .out(M_bobo5_out)
  );
  
  wire [1-1:0] M_bobo6_out;
  reg [4-1:0] M_bobo6_alufn;
  reg [2-1:0] M_bobo6_a;
  boole1_24 bobo6 (
    .alufn(M_bobo6_alufn),
    .a(M_bobo6_a),
    .out(M_bobo6_out)
  );
  
  wire [1-1:0] M_bobo7_out;
  reg [4-1:0] M_bobo7_alufn;
  reg [2-1:0] M_bobo7_a;
  boole1_24 bobo7 (
    .alufn(M_bobo7_alufn),
    .a(M_bobo7_a),
    .out(M_bobo7_out)
  );
  
  always @* begin
    M_bobo0_alufn = alufn;
    M_bobo1_alufn = alufn;
    M_bobo2_alufn = alufn;
    M_bobo3_alufn = alufn;
    M_bobo4_alufn = alufn;
    M_bobo5_alufn = alufn;
    M_bobo6_alufn = alufn;
    M_bobo7_alufn = alufn;
    M_bobo0_a[0+0-:1] = a[0+0-:1];
    M_bobo1_a[0+0-:1] = a[1+0-:1];
    M_bobo2_a[0+0-:1] = a[2+0-:1];
    M_bobo3_a[0+0-:1] = a[3+0-:1];
    M_bobo4_a[0+0-:1] = a[4+0-:1];
    M_bobo5_a[0+0-:1] = a[5+0-:1];
    M_bobo6_a[0+0-:1] = a[6+0-:1];
    M_bobo7_a[0+0-:1] = a[7+0-:1];
    M_bobo0_a[1+0-:1] = b[0+0-:1];
    M_bobo1_a[1+0-:1] = b[1+0-:1];
    M_bobo2_a[1+0-:1] = b[2+0-:1];
    M_bobo3_a[1+0-:1] = b[3+0-:1];
    M_bobo4_a[1+0-:1] = b[4+0-:1];
    M_bobo5_a[1+0-:1] = b[5+0-:1];
    M_bobo6_a[1+0-:1] = b[6+0-:1];
    M_bobo7_a[1+0-:1] = b[7+0-:1];
    out[0+0-:1] = M_bobo0_out;
    out[1+0-:1] = M_bobo1_out;
    out[2+0-:1] = M_bobo2_out;
    out[3+0-:1] = M_bobo3_out;
    out[4+0-:1] = M_bobo4_out;
    out[5+0-:1] = M_bobo5_out;
    out[6+0-:1] = M_bobo6_out;
    out[7+0-:1] = M_bobo7_out;
  end
endmodule
