/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [7-1:0] M_seg_seg;
  wire [4-1:0] M_seg_sel;
  reg [16-1:0] M_seg_values;
  multi_seven_seg_2 seg (
    .clk(clk),
    .rst(rst),
    .values(M_seg_values),
    .seg(M_seg_seg),
    .sel(M_seg_sel)
  );
  
  wire [8-1:0] M_alle_out;
  reg [8-1:0] M_alle_a;
  reg [8-1:0] M_alle_b;
  reg [8-1:0] M_alle_alufn;
  alu8_3 alle (
    .a(M_alle_a),
    .b(M_alle_b),
    .alufn(M_alle_alufn),
    .out(M_alle_out)
  );
  
  wire [16-1:0] M_conv_decimalOutput;
  reg [8-1:0] M_conv_binaryInput;
  converter_4 conv (
    .binaryInput(M_conv_binaryInput),
    .decimalOutput(M_conv_decimalOutput)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = ~M_seg_seg;
    io_sel = ~M_seg_sel;
    M_alle_a = io_dip[0+7-:8];
    M_alle_b = io_dip[8+7-:8];
    M_alle_alufn = io_dip[16+7-:8];
    M_conv_binaryInput = M_alle_out;
    M_seg_values = M_conv_decimalOutput;
  end
endmodule
