/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  wire [8-1:0] M_duadd_sum;
  wire [1-1:0] M_duadd_z;
  wire [1-1:0] M_duadd_v;
  wire [1-1:0] M_duadd_n;
  reg [8-1:0] M_duadd_a;
  reg [8-1:0] M_duadd_b;
  reg [1-1:0] M_duadd_alufn0;
  mojo_8bitfulladder_2 duadd (
    .a(M_duadd_a),
    .b(M_duadd_b),
    .alufn0(M_duadd_alufn0),
    .sum(M_duadd_sum),
    .z(M_duadd_z),
    .v(M_duadd_v),
    .n(M_duadd_n)
  );
  
  always @* begin
    M_duadd_a = io_dip[0+7-:8];
    M_duadd_b = io_dip[8+7-:8];
    M_duadd_alufn0 = io_dip[16+0+0-:1];
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    io_led[0+7-:8] = M_duadd_sum;
    io_led[8+0+0-:1] = M_duadd_z;
    io_led[8+1+0-:1] = M_duadd_v;
    io_led[8+2+0-:1] = M_duadd_n;
  end
endmodule
