/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifterleft_2 (
    input [7:0] a,
    input [2:0] b,
    output reg [7:0] out
  );
  
  
  
  reg [7:0] w;
  
  reg [7:0] x;
  
  reg [7:0] y;
  
  reg [7:0] z;
  
  always @* begin
    out = 1'h0;
    w = 1'h0;
    x = 1'h0;
    y = 1'h0;
    z = 1'h0;
    if (b[2+0-:1]) begin
      w[4+3-:4] = a[0+3-:4];
    end else begin
      w = a;
    end
    if (b[1+0-:1]) begin
      x[2+5-:6] = w[0+5-:6];
    end else begin
      x = w;
    end
    if (b[0+0-:1]) begin
      out[1+6-:7] = x[0+6-:7];
    end else begin
      out = x;
    end
  end
endmodule
