/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_2 (
    input [7:0] a,
    input [2:0] b,
    input [1:0] alufn,
    output reg [7:0] out
  );
  
  
  
  reg [7:0] na;
  
  reg [7:0] w;
  
  reg [7:0] x;
  
  reg [7:0] y;
  
  wire [8-1:0] M_flip_out;
  reg [8-1:0] M_flip_a;
  flipper8_3 flip (
    .a(M_flip_a),
    .out(M_flip_out)
  );
  
  wire [8-1:0] M_flip2_out;
  reg [8-1:0] M_flip2_a;
  flipper8_3 flip2 (
    .a(M_flip2_a),
    .out(M_flip2_out)
  );
  
  always @* begin
    M_flip_a = a;
    out = {4'h8{alufn[1+0-:1] & a[7+0-:1]}};
    w = {4'h8{alufn[1+0-:1] & a[7+0-:1]}};
    x = {4'h8{alufn[1+0-:1] & a[7+0-:1]}};
    y = {4'h8{alufn[1+0-:1] & a[7+0-:1]}};
    if (alufn[0+0-:1]) begin
      na = M_flip_out;
    end else begin
      na = a;
    end
    if (b[2+0-:1]) begin
      w[4+3-:4] = na[0+3-:4];
    end else begin
      w = na;
    end
    if (b[1+0-:1]) begin
      x[2+5-:6] = w[0+5-:6];
    end else begin
      x = w;
    end
    if (b[0+0-:1]) begin
      y[1+6-:7] = x[0+6-:7];
    end else begin
      y = x;
    end
    M_flip2_a = y;
    if (alufn[0+0-:1]) begin
      out = M_flip2_out;
    end else begin
      out = y;
    end
  end
endmodule
