/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boole1_19 (
    input [3:0] alufn,
    input [1:0] a,
    output reg out
  );
  
  
  
  wire [1-1:0] M_muxx_out;
  reg [4-1:0] M_muxx_a;
  reg [2-1:0] M_muxx_sel;
  multiplexer4_18 muxx (
    .a(M_muxx_a),
    .sel(M_muxx_sel),
    .out(M_muxx_out)
  );
  
  always @* begin
    M_muxx_a = alufn;
    M_muxx_sel = a;
    out = M_muxx_out;
  end
endmodule
