/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_fullAdder_9 (
    input [2:0] a,
    output reg sum,
    output reg carry
  );
  
  
  
  always @* begin
    sum = (a[0+0-:1] ^ a[1+0-:1]) ^ (a[2+0-:1]);
    carry = (((a[0+0-:1] ^ a[1+0-:1]) & a[2+0-:1]) | (a[0+0-:1] & a[1+0-:1]));
  end
endmodule
