/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiplexer4_18 (
    input [3:0] a,
    input [1:0] sel,
    output reg out
  );
  
  
  
  always @* begin
    out = a[(sel)*1+0-:1];
  end
endmodule
