/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mux4_8bit_3 (
    input [31:0] a,
    input [1:0] sel,
    output reg [7:0] out
  );
  
  
  
  always @* begin
    out = a[(sel)*8+7-:8];
  end
endmodule
